
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oneliner-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oneliner-api-gateway
  template:
    metadata:
      labels:
        app: oneliner-api-gateway
    spec:
      containers:
        - name: oneliner-api-gateway
          image: avinashkallingal/oneliner-api-gateway:latest
          ports:
            - containerPort: 4000
          env:
          - name: PORT
            valueFrom:
              secretKeyRef:
                name: oneliner-secrets
                key: API_GATEWAY_PORT
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: oneliner-secrets
                key: JWT_SECRET
          - name: FRONTEND_URL
            valueFrom:
              secretKeyRef:
                name: oneliner-secrets
                key: FRONTEND_URL
          - name: RABBITMQ_URL
            valueFrom:
              secretKeyRef:
                name: oneliner-secrets
                key: RABBITMQ_URL
---
apiVersion: v1
kind: Service
metadata:
  name: oneliner-api-gateway-service
spec:
  type: NodePort
  selector:
    app: oneliner-api-gateway
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
    nodePort: 32000