apiVersion: apps/v1
kind: Deployment
metadata:
  name: oneliner-post-service
spec:
  selector:
    matchLabels:
      app: oneliner-post-service
  replicas: 1
  template:
    metadata:
      labels:
        app: oneliner-post-service
    spec:
      containers:
        - name: oneliner-post-service
          image: avinashkallingal/oneliner-post-service:latest
          ports:
            - containerPort: 5002
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: oneliner-secrets
                  key: POST_PORT
            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  name: oneliner-secrets
                  key: POST_DB_URI
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: oneliner-secrets
                  key: RABBITMQ_URL
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: oneliner-secrets
                  key: S3_ACCESS_KEY
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: oneliner-secrets
                  key: S3_SECRET_ACCESS_KEY
            - name: S3_BUCKETNAME
              valueFrom:
                secretKeyRef:
                  name: oneliner-secrets
                  key: S3_BUCKETNAME
            - name: S3_BUCKET_REGION
              valueFrom:
                secretKeyRef:
                  name: oneliner-secrets
                  key: S3_BUCKET_REGION

---

apiVersion: v1
kind: Service
metadata:
  name: oneliner-post-service
spec:
  type: ClusterIP
  selector:
    app: oneliner-post-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002