apiVersion: apps/v1
kind: Deployment
metadata:
  name: oneliner-user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oneliner-user-service
  template:
    metadata:
      labels:
        app: oneliner-user-service
    spec:
      containers:
        - name: oneliner-user-service
          image: avinashkallingal/oneliner-user-service:latest
          ports:
            - containerPort: 5001
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: oneliner-secrets
                  key: USER_PORT
            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  name: oneliner-secrets
                  key: USER_DB_URI
            - name: SMTP_MAIL
              valueFrom:
                secretKeyRef:
                  name: oneliner-secrets
                  key: SMTP_MAIL
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oneliner-secrets
                  key: SMTP_PASSWORD
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: oneliner-secrets
                  key: RABBITMQ_URL
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: oneliner-secrets
                  key: S3_ACCESS_KEY
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: oneliner-secrets
                  key: S3_SECRET_ACCESS_KEY
            - name: S3_BUCKETNAME
              valueFrom:
                secretKeyRef:
                  name: oneliner-secrets
                  key: S3_BUCKETNAME
            - name: S3_BUCKET_REGION
              valueFrom:
                secretKeyRef:
                  name: oneliner-secrets
                  key: S3_BUCKET_REGION
            
---

apiVersion: v1
kind: Service
metadata:
  name: oneliner-user-service
spec:
  type: ClusterIP
  selector:
    app: oneliner-user-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001